#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IRIS_HOME=${IRIS_HOME:-`cd $DIR/.. && pwd -P`}
NODEDIR=$IRIS_HOME/nodejs
CONFDIR=$IRIS_HOME/conf
SVC_DIR=$NODEDIR/services
SVC_CONF=$CONFDIR/services.conf
LOGDIR=$IRIS_HOME/logs
PIDFILE=$LOGDIR/iris.pid
mkdir -p $LOGDIR

function iris_pid {
    pid=''
    if [ -e "$PIDFILE" ]; then
        pid=$(xargs ps u -p < $PIDFILE | awk '!/PID/ {print $2}')
    fi
    echo $pid
}

function start_services {
    if [ ! -e "$SVC_CONF" ]; then
        echo "Service configuration [$SVC_CONF] cannot be found!"
        iris_cmd_help
        exit 1
    fi
    echo "Starting services:"
    cat $SVC_CONF | sed 's/[#;].*$//' | (while read line
        do
            [ -z "$line" ] && continue
            local service=($line)
            local port=${service[0]}
            local name=${service[1]}
            local nodefile=${service[2]}
            local conffile=${service[3]}
            local log=$LOGDIR/$name.log
            NODE_PORT=$port node $SVC_DIR/$nodefile $CONFDIR/$conffile > $log &
            printf "%-12s http://localhost:%s\n" "[$name]" $port
        done
        wait
    ) &
    irispid=$!
}

function iris_cmd_start {
    pid=`iris_pid`
    if [ -n "$pid" ]; then
        echo "Iris is already running (pid `cat $PIDFILE`)"
    else
        start_services
        if [ -n "$irispid" ]; then
            echo $irispid > $PIDFILE
            iris_cmd_status
        else
            echo "Error launching Iris"
        fi
    fi
}

function iris_cmd_stop {
    pid=`iris_pid`
    if [ -n "$pid" ]; then
        # Kill children
        ps -o pid,ppid -ax | awk "\$2==$pid{print \$1}" | xargs kill
        echo "Iris successfully stopped."
    else
        echo "Iris is not running. Nothing to stop."
    fi
    # Handle both standard shutdown and when Iris is not running but the
    # pid file still exists.
    if [ -e "$PIDFILE" ]; then
        rm $PIDFILE
    fi
}

function iris_cmd_install {
    cd $IRIS_HOME
    installlog=$LOGDIR/install.log
    [ -e "$installlog" ] && rm $installlog
    # Fetch git-managed modules
    
    echo "Installing Git modules..."
    git submodule init 2>&1 >> $installlog
    git submodule update 2>&1 >> $installlog

    echo "Installing Node modules..."
    # Install Node.js dependencies
    cd $IRIS_HOME/nodejs
    npm install 2>&1 >> $installlog
    
    echo "Compiling jQuery library..."
    # Compile jQuery library
    cd $IRIS_HOME/external/jquery
    git submodule update --init 2>&1 >> $installlog
    make 2>&1 >> $installlog
    
    echo "Compiling Fastbit... (Hang on. This might take a while.)"
    # Install FastBit
    cd $IRIS_HOME/fastbit
    ./configure --prefix $IRIS_HOME 2>&1 >> $installlog
    make 2>&1 >> $installlog # Now take a [long] coffee break
    make check 2>&1 >> $installlog
    make install 2>&1 >> $installlog

}

function iris_cmd_help {
    echo 'iris [options] <command> [<arguments>]
    
Available commands:
    help        This command
    install     Install dependencies required by Iris
    open        Open up an Iris session (Mac only, for now)
    start       Start Iris
    stop        Stop Iris
    restart     Restart Iris
    status      Check whether or not Iris is running
'
}

function iris_cmd_open {
    # TODO: Actually get the web server from configuration
    open http://localhost:4747
}

function iris_cmd_status {
    pid=`iris_pid`
    if [ -z "$pid" ]; then
        echo "Iris is not running."
    else
        nproc=`ps -o ppid -ax | grep -c "^$pid\$"`
        echo "Iris is running as process $pid with $nproc services."
    fi
}

function iris_cmd_restart {
    iris_cmd_stop
    iris_cmd_start
}

cmd=$1
if [ `declare -f iris_cmd_$cmd | wc -l` -gt 1 ]; then
    eval iris_cmd_$cmd
else
    echo "Unrecognized command. Try 'iris help'"
fi
