#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IRIS_HOME=${IRIS_HOME:-`cd $DIR/.. && pwd -P`}
NODEDIR=$IRIS_HOME/nodejs
CONFDIR=$IRIS_HOME/conf
SVC_DIR=$NODEDIR/services
SVC_CONF=$CONFDIR/services.json
LOGDIR=$IRIS_HOME/logs
PIDFILE=$LOGDIR/iris.pid
SVCPIDFILE=$LOGDIR/service.%%.pid
mkdir -p $LOGDIR

function running_pid {
    pidfile=$1
    if [ -e "$pidfile" ]; then
        xargs ps u -p < $pidfile | awk '!/PID/ {print $2}'
    fi
}

function iris_pid {
    running_pid $PIDFILE
}

function svc_pidfile {
    svc=$1
    echo $SVCPIDFILE | sed "s/%%/$svc/"
}

function start_services {
    svc=$1
    if [ ! -e "$SVC_CONF" ]; then
        echo "Service configuration [$SVC_CONF] cannot be found!"
        iris_cmd_help
        exit 1
    fi
    echo "Starting services:"
    if [ -n "$svc" ]; then
        list_services="iris_cmd_services | awk '\$2==\"$svc\"{print}'"
    else
        list_services='iris_cmd_services'
    fi
    eval $list_services | (while read line
        do
            local service=($line)
            local port=${service[0]}
            local name=${service[1]}
            local nodefile=${service[2]}
            local conffile=${service[3]}
            local log=$LOGDIR/$name.log
            pidfile=`svc_pidfile $name`
            pid=`running_pid $pidfile`
            if [ -n "$pid" ]; then
                echo "Service $name is already running as process $pid"
                continue
            fi
            NODE_PORT=$port node $SVC_DIR/$nodefile $CONFDIR/$conffile > $log &
            echo $! > $pidfile
            printf "%-20s http://localhost:%s\n" "[$name]" $port
        done
        wait
    ) &
    sleep 1
    irispid=$!
}

function start_all_iris {
    pid=`iris_pid`
    if [ -n "$pid" ]; then
        echo "Iris is already running (pid `cat $PIDFILE`)"
    else
        start_services
        if [ -n "$irispid" ]; then
            echo $irispid > $PIDFILE
            iris_cmd_status
        else
            echo "Error launching Iris"
        fi
    fi
}

function iris_cmd_start {
    svc=$1
    if [ -n "$svc" ]; then
        if [ `iris_cmd_services | cut -f2 | grep -c "\b$svc\b"` -eq 0 ]; then
            echo "Service $svc is not a valid service!"
            exit 1
        fi
        pidfile=`svc_pidfile $svc`
        pid=`running_pid $pidfile`
        if [ -n "$pid" ]; then
            echo "Service $svc is already running!"
            return
        fi
        start_services $svc
    else
        start_all_iris
    fi
}

function iris_cmd_stop {
    svc=$1
    if [ -n "$svc" ]; then
        if [ `iris_cmd_services | cut -f2 | grep -c "\b$svc\b"` -eq 0 ]; then
            echo "Service $svc is not a valid service!"
            exit 1
        else
            pidfile=`svc_pidfile $svc`
            if [ ! -e "$pidfile" ]; then
                echo "Service $svc is not running!"
                return
            fi
            kill `running_pid $pidfile`
            rm -f $pidfile
            echo "Stopped service $svc."
        fi
    else
        pid=`iris_pid`
        if [ -n "$pid" ]; then
            # Kill children
            ps -o pid,ppid -ax | awk "\$2==$pid{print \$1}" | xargs kill
            # In case services are started separately
            for pidfile in `svc_pidfile '*'`; do
                pid=`running_pid $pidfile`
                # Kill standalone service process
                if [ -n "$pid" ]; then
                    kill $pid
                fi
            done
            echo "Iris successfully stopped."
        else
            echo "Iris is not running. Nothing to stop."
        fi
        # Handle both standard shutdown and when Iris is not running but the
        # pid file still exists.
        rm -f $PIDFILE `svc_pidfile '*'`
    fi 
}

function iris_cmd_install {
    cd $IRIS_HOME
    installlog=$LOGDIR/install.log
    [ -e "$installlog" ] && rm $installlog
    # Fetch git-managed modules
    
    echo "Installing Git modules..."
    git submodule init 2>&1 >> $installlog
    git submodule update 2>&1 >> $installlog

    echo "Installing Node modules..."
    # Install Node.js dependencies
    cd $IRIS_HOME/nodejs
    npm install 2>&1 >> $installlog
    
    echo "Compiling jQuery library..."
    # Compile jQuery library
    cd $IRIS_HOME/external/jquery
    git submodule update --init 2>&1 >> $installlog
    make 2>&1 >> $installlog
    
    echo "Compiling Fastbit... (Hang on. This might take a while.)"
    # Install FastBit
    cd $IRIS_HOME/fastbit
    ./configure --prefix $IRIS_HOME 2>&1 >> $installlog
    make 2>&1 >> $installlog # Now take a [long] coffee break
    make check 2>&1 >> $installlog
    make install 2>&1 >> $installlog

}

function iris_cmd_help {
    echo 'iris [options] <command> [<arguments>]
    
Available commands:
    help        This command
    install     Install dependencies required by Iris
    open        Open up an Iris session (Mac only, for now)
    start       Start Iris
    stop        Stop Iris
    restart     Restart Iris
    services    Lists available services
    status      Check whether or not Iris is running
'
}

function iris_cmd_open {
    # TODO: Actually get the web server from configuration
    open http://localhost:4747
}

function iris_cmd_status {
    pid=`iris_pid`
    if [ -z "$pid" ]; then
        echo "Iris is not running."
    else
        nproc=`ps -o ppid -ax | grep -c "\b$pid\b"`
        echo "Iris is running as process $pid with $nproc services."
    fi
}

function iris_cmd_services {
    _json_flatten $SVC_CONF "services" "port name nodefile config"
}

function iris_cmd_restart {
    iris_cmd_stop "$@"
    iris_cmd_start "$@"
}

function _json_flatten {
    jsonfile=$1
    key=$2
    fields=$3
    perl -MJSON -e "
        my \$d = decode_json(join '',<STDIN>)->{$key};
        print
            join(\"\n\",
                map {
                    my \$j=\$_; join(\"\t\",
                        map { \$j->{\$_} } qw/$fields/
                    )
                } @\$d), \"\n\"
    " < $SVC_CONF
}

cmd=$1
if [ `declare -f iris_cmd_$cmd | wc -l` -gt 1 ]; then
    shift
    eval "iris_cmd_$cmd \"$@\""
else
    echo "Unrecognized command. Try 'iris help'"
fi
