#!/bin/sh

# Old version used for some validation
old_version=$1;
new_version=$2;
if [ -z "$old_version" ] || [ -z "$new_version" ]; then
    echo "Usage: $0 old-version-number new-version-number"
    exit 1
fi
perl -pi -e \
    "s/^(\s*[\s\W]*\"version\"\s*:\s*)\"$old_version\"/\$1\"$new_version\"/" \
    package.json
perl -pi -e \
    "s/^(\s*[\s\W]*\"version\"\s*:\s*)\"$old_version\"/\$1\"$new_version\"/" \
    bower.json
perl -pi -e "s/^\*\*Version $old_version\*\*$/**Version $new_version**/" \
    README.md
